name: Landing

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - 'LANDING.md'


jobs:
  parse-landing:
    uses: baikinkirill/Landing-Front/.github/workflows/updateProjectsInfo.yml@master
    with:
      username: mona
    secrets:
      envPAT: ${{ secrets.GITHUB_TOKEN }}
      
